#open tmux at startup                              
if command -v tmux>/dev/null; then
 [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && tmux
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export BROWSER="/usr/bin/firefox"

alias vim=nvim
alias obi=Obsidian-1.3.7.AppImage
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

ZSH_THEME="cloud"

plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# The following three lines are used for erroneous % at beginning of new prompt
setopt PROMPT_CR
setopt PROMPT_SP
export PROMPT_EOL_MARK=""

# Install Ruby Gems to ~/gems
export GEM_HOME="$HOME/gems"
export PATH="$HOME/gems/bin:$PATH"

# Needed for gems to be executable
export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"
